---
# Source: omnix/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-application
  namespace: default
  labels:
    app: my-application
    app: my-app
    environment: production
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: my-application
    app: my-app
    environment: production
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
# Source: omnix/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  namespace: default
  labels:
    app: my-application
    app: my-app
    environment: production
    deployment-label: custom-deployment
  annotations:
    description: "Example deployment"

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-application
      pod-label: custom-pod
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-application
        pod-label: custom-pod
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: my-application
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
