{{- if .Values.hpa.enable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "omnix.fullname" $ }}
  namespace: {{ include "omnix.namespace" $}}
  labels:
    app: {{ include "omnix.fullname" $ }}
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value }}
    {{- end}}
    {{- range $key, $value := .Values.hpa.labels }}
    {{ $key}}: {{ $value}}
    {{- end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "omnix.fullname" $ }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1}}
  maxReplicas: {{ .Values.hpa.maxReplicas | default (mul .Values.replicaCount 2)}}
  metrics: 
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage | default 50}}
  - type: Resource 
    resource: 
      name: memory 
      target: 
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage | default 50}}
  # TODO: Add behavior
{{- end}}