{{- with .Values.envFrom }}
  {{- range . }}
    {{- if eq .type "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "omnix.namespace" $ }}
type: {{ .secretType | default "Opaque" }}
stringData:
  {{- range .files }}
{{ $.Files.Get .path | indent 2 }}
  {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
