{{- with .Values.serviceAccount }}
{{- if .enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omnix.fullname" $ }}
  namespace: {{ include "omnix.namespace" $}}
  labels:
    app: {{ include "omnix.fullname" $ }}
    {{- range $key, $value := $.Values.global.labels }}
    {{ $key}}: {{ $value }}
    {{- end}}
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{- end}}
  {{- with .annotations }}
  annotations:
    {{- range $key, $value := .}}
    {{ $key }}: {{ $value | quote }}
    {{- end}}
  {{- end}}
{{- end}}
{{- end}}